# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

# estratégia para ativar a integração contínua: Quando (on)
on: # QUANDO
  push: # UM git push FOR EXECUTADO
    branches: [ "main" ] # NA BRANCH MAIN ... ENTÃO EXECUTAR OS PIPELINE DE TESTES
  pull_request: # OU QUANDO UM PULL_REQUEST FOR EXECUTADO
    branches: [ "main" ] # NA BRANCH MAIN ... ENTÃO EXECUTAR OS PIPELINE DE TESTES

jobs:
  build:
    # qual máquina docker será utilizada para executar os testes?
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # qual versão do nodejs usar? pode testar com mais de uma versão.
        # node-version: [18.x, 20.x, 22.x]
        node-version: [22.x]

    steps:
      # DEVERÁ FAZER O CHECKOUT (GIT CLONE)
    - uses: actions/checkout@v4
      
      # DEVERÁ INSTALAR O NPM
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

      # DEVERÁ EXECUTAR: NPM INSTALL
    - run: npm ci

      # DEVERÁ EXECUTAR: NPM RUN BUILD
      #     CASO ESTE SCRIPT ESTEJA DEFINIDO NO ARQUIVO PACKAGE.JSON
    - run: npm run build --if-present

      # DEVERÁ EXECUTAR TODOS OS TESTES: NPM TEST
    - run: npm test
